// <auto-generated />
using System;
using LLMProxy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LLMProxy.Infrastructure.Persistence.Migrations.Sqlite
{
    [DbContext(typeof(SqliteGatewayDbContext))]
    [Migration("20260924104327_ProviderKeyPools")]
    partial class ProviderKeyPools
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("LLMProxy.Domain.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedModels")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("BudgetUnits")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastUsedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MonthlyBudgetUnits")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MonthlyTokenLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestsPerMinute")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReservedTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReservedUnits")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SpentUnits")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TokenLimit")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UsedTokens")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("Owner");

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("LLMProxy.Domain.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt", "Id");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("LLMProxy.Domain.BatchItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LeaseExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BatchId", "Index")
                        .IsUnique();

                    b.HasIndex("Status", "LeaseExpiresAt");

                    b.ToTable("batch_items", (string)null);
                });

            modelBuilder.Entity("LLMProxy.Domain.BatchJob", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApiKeyId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorFileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Failed")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FinishedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InputFileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputFileId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<int>("Total")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyId", "CreatedAt", "Id");

                    b.ToTable("batch_jobs", (string)null);
                });

            modelBuilder.Entity("LLMProxy.Domain.GatewayFile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApiKeyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BatchId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("Bytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ErrorsOnly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyId", "CreatedAt", "Id");

                    b.ToTable("gateway_files", (string)null);
                });

            modelBuilder.Entity("LLMProxy.Domain.OperatorAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("operators", (string)null);
                });

            modelBuilder.Entity("LLMProxy.Domain.OperatorSession", b =>
                {
                    b.Property<string>("TokenHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("TEXT");

                    b.HasKey("TokenHash");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("OperatorId");

                    b.ToTable("operator_sessions", (string)null);
                });

            modelBuilder.Entity("LLMProxy.Domain.QuotaReservation", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApiKeyId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CostUnits")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuotaPeriod")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<long>("Tokens")
                        .HasColumnType("INTEGER");

                    b.HasKey("RequestId");

                    b.HasIndex("ApiKeyId");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("quota_reservations", (string)null);
                });

            modelBuilder.Entity("LLMProxy.Domain.QuotaWindow", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApiKeyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Period")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<long>("ReservedTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReservedUnits")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SpentUnits")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UsedTokens")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyId", "Period")
                        .IsUnique();

                    b.ToTable("quota_windows", (string)null);
                });

            modelBuilder.Entity("LLMProxy.Domain.ReconciliationRecord", b =>
                {
                    b.Property<string>("Reference")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ActualCost")
                        .HasPrecision(20, 9)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Reference");

                    b.HasIndex("AttemptId")
                        .IsUnique();

                    b.ToTable("billing_reconciliations", (string)null);
                });

            modelBuilder.Entity("LLMProxy.Domain.RetiredKeyCredential", b =>
                {
                    b.Property<string>("KeyHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApiKeyId")
                        .HasColumnType("TEXT");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("KeyHash");

                    b.HasIndex("ApiKeyId");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("retired_credentials", (string)null);
                });

            modelBuilder.Entity("LLMProxy.Domain.UpstreamAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ActualCost")
                        .HasPrecision(20, 9)
                        .HasColumnType("TEXT");

                    b.Property<long>("CacheCreationTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CachedInputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("EstimatedCost")
                        .HasPrecision(20, 9)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKeyId")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderRequestId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("UsageEstimated")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RequestId", "CreatedAt");

                    b.ToTable("upstream_attempts", (string)null);
                });

            modelBuilder.Entity("LLMProxy.Domain.UsageRecord", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApiKeyId")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedCost")
                        .HasPrecision(20, 9)
                        .HasColumnType("TEXT");

                    b.Property<long>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalTokens")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UsageEstimated")
                        .HasColumnType("INTEGER");

                    b.HasKey("RequestId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ApiKeyId", "CreatedAt");

                    b.HasIndex("CreatedAt", "RequestId");

                    b.ToTable("usage_records", (string)null);
                });

            modelBuilder.Entity("LLMProxy.Domain.BatchItem", b =>
                {
                    b.HasOne("LLMProxy.Domain.BatchJob", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LLMProxy.Domain.BatchJob", b =>
                {
                    b.HasOne("LLMProxy.Domain.ApiKey", null)
                        .WithMany()
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LLMProxy.Domain.OperatorSession", b =>
                {
                    b.HasOne("LLMProxy.Domain.OperatorAccount", null)
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LLMProxy.Domain.QuotaReservation", b =>
                {
                    b.HasOne("LLMProxy.Domain.ApiKey", null)
                        .WithMany()
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LLMProxy.Domain.QuotaWindow", b =>
                {
                    b.HasOne("LLMProxy.Domain.ApiKey", null)
                        .WithMany()
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LLMProxy.Domain.RetiredKeyCredential", b =>
                {
                    b.HasOne("LLMProxy.Domain.ApiKey", null)
                        .WithMany()
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LLMProxy.Domain.UsageRecord", b =>
                {
                    b.HasOne("LLMProxy.Domain.ApiKey", null)
                        .WithMany()
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
