version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: docker
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: npm
    directory: /examples/typescript
    schedule: { interval: weekly }
  - package-ecosystem: pip
    directory: /examples/python
    schedule: { interval: weekly }
