// <auto-generated />
using System;
using LLMProxy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LLMProxy.Infrastructure.Persistence.Migrations.Postgres
{
    [DbContext(typeof(PostgresGatewayDbContext))]
    partial class PostgresGatewayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LLMProxy.Domain.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedModels")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("BudgetUnits")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("RequestsPerMinute")
                        .HasColumnType("integer");

                    b.Property<long>("ReservedTokens")
                        .HasColumnType("bigint");

                    b.Property<long>("ReservedUnits")
                        .HasColumnType("bigint");

                    b.Property<long>("SpentUnits")
                        .HasColumnType("bigint");

                    b.Property<long?>("TokenLimit")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UsedTokens")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("Owner");

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("LLMProxy.Domain.QuotaReservation", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApiKeyId")
                        .HasColumnType("uuid");

                    b.Property<long>("CostUnits")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("Tokens")
                        .HasColumnType("bigint");

                    b.HasKey("RequestId");

                    b.HasIndex("ApiKeyId");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("quota_reservations", (string)null);
                });

            modelBuilder.Entity("LLMProxy.Domain.UsageRecord", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApiKeyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("EstimatedCost")
                        .HasPrecision(20, 9)
                        .HasColumnType("numeric(20,9)");

                    b.Property<long>("InputTokens")
                        .HasColumnType("bigint");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("bigint");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<long>("TotalTokens")
                        .HasColumnType("bigint");

                    b.Property<bool>("UsageEstimated")
                        .HasColumnType("boolean");

                    b.HasKey("RequestId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ApiKeyId", "CreatedAt");

                    b.ToTable("usage_records", (string)null);
                });

            modelBuilder.Entity("LLMProxy.Domain.QuotaReservation", b =>
                {
                    b.HasOne("LLMProxy.Domain.ApiKey", null)
                        .WithMany()
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LLMProxy.Domain.UsageRecord", b =>
                {
                    b.HasOne("LLMProxy.Domain.ApiKey", null)
                        .WithMany()
                        .HasForeignKey("ApiKeyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
