"""Exercise two gateway processes, Redis loss, crash recovery and PostgreSQL backup restoration."""
import argparse
import importlib.util
import json
import os
import signal
import socket
import subprocess
import sys
import tempfile
import threading
import time
import urllib.error
import urllib.request
import uuid
from http.server import ThreadingHTTPServer
from pathlib import Path

from load_probe import probe
from smoke_common import ADMIN_KEY, KEY, ROOT, isolated_environment, provider_environment, request, wait_ready
from source_smoke import free_port


def postgres(sql, database="postgres"):
    # Database names are generated by this script; connection credentials stay in libpq environment variables.
    result = subprocess.run(["psql", "--no-psqlrc", "--no-password", "-v", "ON_ERROR_STOP=1", "-At",
                             "--dbname", database, "-c", sql], capture_output=True, text=True, check=True, timeout=30)
    return result.stdout.strip()


def stop(process, kill=False):
    if process.poll() is None:
        process.kill() if kill else process.terminate()
        try:
            process.wait(timeout=50)
        except subprocess.TimeoutExpired:
            process.kill()
            process.wait(timeout=10)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--duration", type=float, default=60)
    parser.add_argument("--long-stream-seconds", type=float, default=30)
    parser.add_argument("--output", type=Path, default=ROOT / "artifacts/recovery-drill.json")
    args = parser.parse_args()
    if args.duration <= 0 or not 1 <= args.long_stream_seconds <= 120:
        parser.error("Use positive duration and a long stream of 1–120 seconds")
    name = "llmproxy_drill_" + uuid.uuid4().hex
    restored = name + "_restore"
    server_dll = ROOT / "src/LLMProxy.Server/bin/Release/net10.0/LLMProxy.Server.dll"
    report, processes, mock = {}, [], None
    postgres('CREATE DATABASE "' + name + '"')
    try:
        postgres('CREATE DATABASE "' + restored + '"')
        with tempfile.TemporaryDirectory(prefix="llmproxy-recovery-") as temporary:
            folder = Path(temporary)
            redis_port, mock_port = free_port(), free_port()
            spec = importlib.util.spec_from_file_location("fixture", ROOT / "tests/docker/mock_server.py")
            fixture = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(fixture)
            fixture.Handler.long_stream_seconds = args.long_stream_seconds
            mock = ThreadingHTTPServer(("127.0.0.1", mock_port), fixture.Handler)
            threading.Thread(target=mock.serve_forever, daemon=True).start()
            with (folder / "services.log").open("w") as log:
                def redis():
                    process = subprocess.Popen(["redis-server", "--bind", "127.0.0.1", "--port", str(redis_port),
                                                "--dir", temporary, "--save", "", "--appendonly", "yes"],
                                               stdout=log, stderr=log)
                    processes.append(process)
                    for _ in range(100):
                        try:
                            with socket.create_connection(("127.0.0.1", redis_port), timeout=.1):
                                return process
                        except OSError:
                            time.sleep(.05)
                    raise AssertionError("Fixture Redis did not start")

                redis_process = redis()
                connection = {"Host": os.environ.get("PGHOST", "127.0.0.1"), "Port": os.environ.get("PGPORT", "5432"),
                              "Username": os.environ.get("PGUSER", "postgres"), "Password": os.environ.get("PGPASSWORD", ""),
                              "Database": name}
                environment = isolated_environment()
                environment.update(provider_environment("openai", f"http://127.0.0.1:{mock_port}"))
                environment.update({
                    "ASPNETCORE_HTTP_PORTS": "", "ASPNETCORE_HTTPS_PORTS": "", "OTEL_EXPORTER_OTLP_ENDPOINT": "",
                    "LLMProxy__Storage__Mode": "PostgreSql", "LLMProxy__Storage__AutoMigrate": "true",
                    "ConnectionStrings__Postgres": ";".join(key + '="' + value.replace('"', '""') + '"' for key, value in connection.items()),
                    "ConnectionStrings__Redis": f"127.0.0.1:{redis_port},abortConnect=false,asyncTimeout=1000,connectTimeout=1000",
                    "LLMProxy__Storage__RedisKeyPrefix": name, "LLMPROXY_BOOTSTRAP_KEY": KEY, "LLMPROXY_ADMIN_KEY": ADMIN_KEY,
                    "LLMProxy__RateLimiting__PerUserRequestsPerMinute": "1000000",
                    "LLMProxy__Models__fast__RequestsPerMinute": "1000000", "LLMProxy__Batches__Workers": "0",
                    "LLMProxy__Requests__TimeoutSeconds": "180", "LLMProxy__Requests__ReservationTtlSeconds": "600",
                    "LLMProxy__Concurrency__PerKeyLimit": "32"})
                urls = [f"http://127.0.0.1:{free_port()}" for _ in range(2)]
                gateways = []
                for url in urls:
                    process = subprocess.Popen(["dotnet", str(server_dll)], cwd=ROOT / "src/LLMProxy.Server",
                                               env={**environment, "ASPNETCORE_URLS": url}, stdout=log, stderr=log)
                    processes.append(process)
                    gateways.append(process)
                    wait_ready(url)
                with request(urls[0], "/admin/keys", key=ADMIN_KEY) as response:
                    key_id = json.load(response)[0]["id"]
                policy = json.dumps({"enabled": True, "allowed_models": ["*"], "requests_per_minute": 1000000,
                                     "monthly_spending_budget": 100, "spending_budget": 100}).encode()
                urllib.request.urlopen(urllib.request.Request(urls[0] + "/admin/keys/" + key_id, data=policy, method="PUT",
                    headers={"Authorization": "Bearer " + ADMIN_KEY, "Content-Type": "application/json"}), timeout=15).close()
                print("Running sustained normal/SSE traffic across two replicas.", flush=True)
                report["load"] = probe(urls, KEY, args.duration, 8)
                assert report["load"]["completed"] >= 20 and report["load"]["error_rate"] == 0, report["load"]
                assert report["load"]["latency_ms"]["p95"] < 2000, report["load"]

                print("Checking a long stream and killing its gateway during another stream.", flush=True)
                body = {"model": "fast", "messages": [{"role": "user", "content": "__long_stream__"}], "stream": True}
                before = time.monotonic()
                req = urllib.request.Request(urls[0] + "/v1/chat/completions", json.dumps(body).encode(),
                    headers={"Authorization": "Bearer " + KEY, "Content-Type": "application/json"})
                with urllib.request.urlopen(req, timeout=150) as response:
                    assert b"data: [DONE]" in response.read()
                report["long_stream_seconds"] = time.monotonic() - before
                assert report["long_stream_seconds"] >= args.long_stream_seconds * .9
                with urllib.request.urlopen(req, timeout=15) as response:
                    assert response.readline().startswith(b"data:")
                    stop(gateways[0], kill=True)
                assert int(postgres("SELECT count(*) FROM quota_reservations", name)) == 1
                # Fast-forward only the isolated fixture's orphan, avoiding a ten-minute TTL wait.
                postgres('UPDATE quota_reservations SET "ExpiresAt" = now() - interval \'1 second\'', name)
                for _ in range(2):
                    subprocess.run(["dotnet", str(server_dll), "reservations", "recover"], cwd=ROOT / "src/LLMProxy.Server",
                                   env=environment, check=True, capture_output=True, timeout=30)
                assert postgres("SELECT count(*) FROM usage_records WHERE \"Status\" = 'abandoned'", name) == "1"
                assert postgres("SELECT count(*) FROM quota_reservations", name) == "0"
                assert postgres('SELECT "ReservedTokens" FROM api_keys', name) == "0"
                report["crash_recovery"] = "orphan charged once; reservations released"

                print("Checking Redis loss and recovery on the surviving replica.", flush=True)
                stop(redis_process)
                try:
                    request(urls[1], "/v1/chat/completions", {"model": "fast", "messages": [{"role": "user", "content": "Hello"}]})
                    raise AssertionError("Admission succeeded while Redis was unavailable")
                except urllib.error.HTTPError as error:
                    assert error.code == 503
                redis_process = redis()
                wait_ready(urls[1])
                with request(urls[1], "/v1/chat/completions", {"model": "fast", "messages": [{"role": "user", "content": "Hello"}]}) as response:
                    assert response.status == 200
                report["redis_recovery"] = "admission failed closed and resumed"
                stop(gateways[1])

                print("Restoring a PostgreSQL backup into a fresh database.", flush=True)
                dump = folder / "gateway.dump"
                subprocess.run(["pg_dump", "--no-password", "--format=custom", "--file", str(dump), "--dbname", name],
                               check=True, capture_output=True, timeout=60)
                subprocess.run(["pg_restore", "--no-password", "--exit-on-error", "--no-owner", "--dbname", restored, str(dump)],
                               check=True, capture_output=True, timeout=60)
                for table in ("api_keys", "usage_records", "quota_windows", "upstream_attempts", "audit_events"):
                    assert postgres("SELECT count(*) FROM " + table, name) == postgres("SELECT count(*) FROM " + table, restored)
                assert postgres('SELECT "UsedTokens", "SpentUnits" FROM api_keys', name) == postgres('SELECT "UsedTokens", "SpentUnits" FROM api_keys', restored)
                report["backup_restore"] = "keys, usage, windows, attempts and audit verified"
                args.output.parent.mkdir(parents=True, exist_ok=True)
                args.output.write_text(json.dumps(report, indent=2) + "\n")
                print(json.dumps(report, indent=2), flush=True)
    finally:
        for process in reversed(processes):
            stop(process)
        if mock:
            mock.shutdown()
            mock.server_close()
        for database in (restored, name):
            postgres('DROP DATABASE IF EXISTS "' + database + '" WITH (FORCE)')


if __name__ == "__main__":
    main()
